import { describe, it, expect } from 'vitest'
import { computeHash, formatAmount2 } from '@/lib/import/hash'

// Golden vectors generated by budget-pipeline/deduplicator.py::compute_hash.
// If these ever diverge, web imports would duplicate CLI-imported history.
const GOLDEN: Array<[string, number, string, string, string]> = [
  ['2026-06-15', 6.5, 'STARBUCKS STORE 123', 'Amex Blue', '80cf28d364a37a4462e67e646aa9505267760916fa94769e8d9da3c845c8e29a'],
  ['2026-06-14', 89.2, 'WHOLE FOODS MARKET', 'Amex Blue', 'a76da63326137e2af2ddd0f81b72b7b4582b7e67b3b9d9bcea8624bcf8e5b10a'],
  ['2026-01-02', 1234.56, 'AMAZON MKTPL*1P66J2KP3', 'Chase Prime', '4c7b1043a8ca1ee71a49a0c115e47d833ae566f4f28e022576531828a7dfede4'],
  ['2026-12-31', 0.99, 'NETFLIX.COM', 'Citi', '1b6d38bd6db8047e278bbbb8bd8a3fbc908187f8ad7778bb4736d52b31c09ff4'],
  ['2026-03-05', 688.76, 'M1 PAYMENTS PPD ID: 8327952000', 'Chase Checking', 'e03c43e9be6ef776eadfb4301471a524dfbdd911cf39e939d7c4c214dc6eb373'],
]

describe('computeHash — parity with Python', () => {
  it.each(GOLDEN)('%s|%s|%s|%s', (date, amount, desc, account, expected) => {
    expect(computeHash(date, amount, desc, account)).toBe(expected)
  })

  it('trims the raw description like Python .strip()', () => {
    expect(computeHash('2026-06-15', 6.5, '  STARBUCKS STORE 123  ', 'Amex Blue')).toBe(GOLDEN[0][4])
  })
})

describe('formatAmount2 — 2-decimal guard', () => {
  it('formats to two decimals', () => {
    expect(formatAmount2(6.5)).toBe('6.50')
    expect(formatAmount2(1234.56)).toBe('1234.56')
  })
  it('rejects values needing rounding (Python/JS diverge here)', () => {
    expect(() => formatAmount2(0.125)).toThrow()
  })
  it('rejects non-finite', () => {
    expect(() => formatAmount2(NaN)).toThrow()
  })
})
